service: ai-art-generator
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getImage:
    handler: index.getImage
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-plugin-typescript
