service: ai-art-generator
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm:GetParameter
          Resource:
          - "arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/open-ai-secret-key"


functions:
  generateArt:
    handler: src/index.generateArt
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-plugin-typescript
